language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  
install:
  - composer install --prefer-source

before_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then PHPUNIT_FLAGS="--coverage-clover coverage.xml"; fi
  - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then vendor/bin/php-cs-fixer fix src --diff --dry-run -v --level=symfony; fi
  - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then vendor/bin/php-cs-fixer fix tests --diff --dry-run -v --level=symfony; fi

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then vendor/bin/phpcs src tests --colors -p -s --extensions=php; fi

after_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
