language: php

sudo: false

php:
  - 7.1
  - 7.2

install:
  # install composer dependencies
  - composer install

script:
  # run tests
  - vendor/bin/phpunit --coverage-clover coverage.xml
  # turn off XDebug
  - phpenv config-rm xdebug.ini || return 0
  # check coding standard (defined in composer.json "scripts" section)
  - composer check-cs
  # check with phpstan (defined in composer.json "scripts" section)
  - composer phpstan
  # run PHP_CodeSniffer with ruleset
  - vendor/bin/phpcs src tests -sp --standard=src/ObjectCalisthenics/ruleset.xml --extensions=php

after_script:
  # upload coverage.xml file to Coveralls to analyze it
  - |
    wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    php coveralls.phar --verbose

# do not send success notifications, they have no value
notifications:
  email:
    on_success: never
