os: linux

language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini

install:
    - composer install --no-progress

jobs:
    include:
        -
            name: 'Unit Tests'
            script:
                - vendor/bin/phpunit

        -
            name: 'Run PHP_CodeSniffer'
            php: 7.3
            script:
                - vendor/bin/phpcs src tests -sp --standard=src/ObjectCalisthenics/ruleset.xml --extensions=php

        -
            name: 'Test Coverage'
            php: 7.3
            script:
                - phpdbg -qrr -d memory_limit=-1 vendor/bin/phpunit --coverage-clover coverage.xml
                # upload coverage.xml file to Coveralls to analyze it
                - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
                - php php-coveralls.phar --verbose

cache:
    directories:
        - $HOME/.composer/cache

# do not send success notifications, they have no value
notifications:
    email:
        on_success: never
