os: linux
language: php

php:
  - '7.2'
  - '7.3'
  - '7.4snapshot'

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - composer install --no-progress

jobs:
    include:
        -
            stage: test
            name: ECS
            php: 7.3
            script:
                - composer check-cs

        -
            name: PHPStan
            php: 7.3
            script:
                - composer phpstan

        -
            name: Rector
            php: 7.3
            script:
                - vendor/bin/rector process src tests --dry-run --config rector-ci.yaml

        -
            name: 'Unit Tests'
            script:
                - vendor/bin/phpunit

        -
            name: 'Run PHP_CodeSniffer'
            php: 7.3
            script:
                - vendor/bin/phpcs src tests -sp --standard=src/ObjectCalisthenics/ruleset.xml --extensions=php

        -
            stage: coverage
            name: 'Test Coverage'
            if: branch = master AND type = push
            before_install:
                - echo "keep xdebug"
            script:
                - vendor/bin/phpunit --coverage-clover coverage.xml
                # upload coverage.xml file to Coveralls to analyze it
                - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
                - php php-coveralls.phar --verbose

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

# do not send success notifications, they have no value
notifications:
    email:
        on_success: never
