name: Code Sniffer Set Run

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    code_sniffer_set_run:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: '7.3'
                    coverage: none # default is xdebug

            -   run: composer install --no-progress
            -   run: vendor/bin/phpcs src tests -sp --standard=src/ObjectCalisthenics/ruleset.xml --extensions=php
