name: Code Analysis

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    matrix:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: 'PHPStan'
                        run: composer phpstan

                    -
                        name: 'ECS'
                        run: composer check-cs

                    -
                        name: 'Rector'
                        run: composer rector

                    -
                        name: 'Code Sniffer Set Run'
                        run: 'vendor/bin/phpcs src tests -sp --standard=src/ObjectCalisthenics/ruleset.xml --extensions=php --colors'

                    -
                        run: |
                            vendor/bin/phpunit --coverage-clover build/logs/clover.xml
                            # upload coverage.xml file to Coveralls to analyze it
                            wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
                            php php-coveralls.phar --verbose
                        env:
                            COVERALLS_REPO_TOKEN: 'SF1yYBjzJXjuKpjaST9stiMgypdzQHMzM'

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: pcov

            -   run: composer install --no-progress

            -
                name: ${{ matrix.actions.name }}
                run: ${{ matrix.actions.run }}
